kuka_trj_screwdriver_hook_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_hook_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations: