kuka_trj_photoneo_scan:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start:
  positions:
  - [1.332131803734, 0.0,-2.705, 2.705, 0.0, -1.57, 0.0]
  - [0.35751980175, 0.0, -2.70526, 1.0852457, 0.33911747, 2.01463356, 0.0]
  velocities:
  accelerations:

kuka_trj_photoneo_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start:
  positions:
  - [1.9819981134299998, 0.0, -2.11900424, 1.1751302, 0.33911747, 1.3273229, 0.0]
  - [1.9819981134299998, 0.0, -1.2894493, 2.4240878, 0.0, -1.176701, 0.0]
  - [1.9819981134299998, -0.43545965, -1.3475687, 2.23821023, -0.53389622, -0.96708694, 1.8675]
  - [1.9819981134299998, -0.44662976, -0.69446651,  2.31971711, -0.44418629, -1.6242034 , 1.5245451 ]
  - [1.9819981134299998, -0.45029495, -0.47595129,  2.24885674, -0.45570547, -1.75702296, 1.45961885]
  - [1.9819981134299998, -0.45570547, -0.17558012,  2.06594624, -0.47403142, -1.86139365, 1.40411738] #inizia discesa sul rack da questo in poi
  - [1.9819981134299998, -0.45570547, -0.17558012,  2.06594624, -0.47403142, -1.86139365, 1.40411738]
  - [1.9819981134299998, -0.40474185, -0.19914207,  1.94743838, -0.40770891, -1.73834793, 1.47794481]
  - [1.9819981134299998, -0.37123153, -0.20629792,  1.84341676, -0.3689626 , -1.63694431, 1.52419604]
  velocities:
  accelerations:

kuka_trj_photoneo_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start:
  positions:
  - [1.9819981134299998, -0.37123153, -0.20629792,  1.84341676, -0.3689626 , -1.63694431, 1.52419604] #copia e incolla dei punti sopra
  - [1.9819981134299998, -0.40474185, -0.19914207,  1.94743838, -0.40770891, -1.73834793, 1.47794481]
  - [1.9819981134299998, -0.45570547, -0.17558012,  2.06594624, -0.47403142, -1.86139365, 1.40411738]
  - [1.9819981134299998, -0.45570547, -0.17558012,  2.06594624, -0.47403142, -1.86139365, 1.40411738]

  velocities:
  
  accelerations:
kuka_trj_screwdriver_hook_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_hook_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
kuka_trj_spreader_hook_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_hook_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_on_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_on_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
comau_trj_suction_hook_rack_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_hook_rack_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_on_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_up:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_cover_drop_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_cover_drop_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
comau_trj_tonnopinza_hook_rack_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_tonnopinza_hook_rack_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_grasp_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_grasp_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

