kuka_trj_photoneo_scan:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_photoneo_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

  kuka_trj_photoneo_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
kuka_trj_screwdriver_hook_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_hook_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_1:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_2:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_approach_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_down_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_up_screw_3:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_screwdriver_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
kuka_trj_spreader_hook_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_hook_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_on_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_on_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_drop_rack_approach:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

kuka_trj_spreader_drop_rack_leave:
  joint_names: [structure_joint_1, kuka_joint1, kuka_joint2, kuka_joint3, kuka_joint4,
    kuka_joint5, kuka_joint6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
comau_trj_suction_hook_rack_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_hook_rack_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_on_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_suction_up:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_cover_drop_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_cover_drop_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:
comau_trj_tonnopinza_hook_rack_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_tonnopinza_hook_rack_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_grasp_approach:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

comau_trj_grasp_leave:
  joint_names: [comau_joint_1, comau_joint_2, comau_joint_3, comau_joint_4, comau_joint_5,
    comau_joint_6]
  time_from_start: []
  positions:

  velocities:
  
  accelerations:

