pybullet_simulation:
  objects:
    can:
      package_name: 'battery_cell_description'
      urdf_file_path: 'urdf/can.urdf'
      mesh_file_path: 'meshes/can.STL'
      mesh_position_offset: [0, 0, -0.0575] # pybullet return the position of object center of mass
      mesh_orientation_offset: [0, 0, 0, 1]
      attached_link: 'gripper_base'
