auto_control_configurations:
  robots:
    comau:
      - "watch"
      # - "ctrl"
      - "trajectory_tracking"
      - "simple_touch"
      - "cartesian_velocity"
      - "cartesian_position"
    kuka:
      - "watch"
      # - "ctrl"
      - "trajectory_tracking"
      - "simple_touch"
      - "cartesian_velocity"
      - "cartesian_position"

  configurations:
    watch:
      components:
      - {hardware_interface: "level0_hw", controller: "js_pub", description: ""}
      - {hardware_interface: "level0_hw", controller: "ft_pub", description: ""}
      hidden: true  # do not appear in the gui
    ctrl:
      depends: ["watch"]
      hidden: true  # do not appear in the gui
      components:
      - {hardware_interface: "level0_hw", controller: "ctrl", description: ""}
    trajectory_tracking:
      hidden: true  # do not appear in the gui
      depends: ["watch"]
      components:
      - {hardware_interface: "level0_hw", controller: "microinterpolator", description: ""}
    simple_touch:
      hidden: true  # do not appear in the gui
      depends: ["cartesian_velocity"]
      components:
      - {hardware_interface: "level1_hw", controller: "simple_touch", description: "", runtime_check: false}
    cartesian_velocity:
      hidden: true  # do not appear in the gui
      depends: ["watch"]
      components:
      - {hardware_interface: "level0_hw", controller: "cartesian_velocity", description: "",  runtime_check: false}
    cartesian_position:
      hidden: true  # do not appear in the gui
      depends: ["watch"]
      components:
      - {hardware_interface: "level0_hw", controller: "cartesian_position", description: "",  runtime_check: true}
