comau_level0_hw:
  remap_source_args:
  - "/comau_level0_hw/microinterpolator/follow_joint_trajectory/cancel"
  - "/comau_level0_hw/microinterpolator/follow_joint_trajectory/feedback"
  - "/comau_level0_hw/microinterpolator/follow_joint_trajectory/goal"
  - "/comau_level0_hw/microinterpolator/follow_joint_trajectory/result"
  - "/comau_level0_hw/microinterpolator/follow_joint_trajectory/status"
  - "/comau_level0_hw/microinterpolator/unscaled_joint_target"
  - "/comau_level0_hw/js_pub/joint_states"
  - "/comau_level0_hw/cartesian_position/relative_move/cancel"
  - "/comau_level0_hw/cartesian_position/relative_move/feedback"
  - "/comau_level0_hw/cartesian_position/relative_move/goal"
  - "/comau_level0_hw/cartesian_position/relative_move/result"
  - "/comau_level0_hw/cartesian_position/relative_move/status"

  remap_target_args:
  - "/comau_controller/follow_joint_trajectory/cancel"
  - "/comau_controller/follow_joint_trajectory/feedback"
  - "/comau_controller/follow_joint_trajectory/goal"
  - "/comau_controller/follow_joint_trajectory/result"
  - "/comau_controller/follow_joint_trajectory/status"
  - "/comau_controller/unscaled_joint_target"
  - "/comau/joint_states"
  - "/comau/relative_move/cancel"
  - "/comau/relative_move/feedback"
  - "/comau/relative_move/goal"
  - "/comau/relative_move/result"
  - "/comau/relative_move/status"

  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: world
    tool_link: nj_flange
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  ft_pub:
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "comau_hw_ft_pub"
    type: "cnr/control/ForceTorquePublisher"
    name: wrench
    published_topic: "/comau_gripper/wrench"

  microinterpolator:
    type: "cnr/control/ScaledFJTPosVelEffController"
    controlled_joints: all
    continuity_order: 1
    appenders: [file, screen]
    levels: [debug, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "microinterpolator"

  cartesian_velocity:
    appenders: [file, screen]
    levels: [debug, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "cartesian_velocity"
    type: cnr/control/CartesianVelocityController
    controlled_joints : all
    kin_update_period : 0.002
    target_twist_topic: /comau/target_cart_twist  # setpoint twist topic name

  cartesian_position:
    appenders: [file, screen]
    levels: [debug, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "cartesian_position"
    type: cnr/control/CartesianPositionController
    controlled_joints : all
    kin_update_period : 0.002

  ctrl:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/comau/joint_target"
    controlled_joint: all
    enable_setpoint_watchdog: false
