comau_level0_hw:
  type           : cnr/control/FakeRobotHW
  appenders      : [file, screen]
  levels         : [debug, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : comau_level0_hw
  sampling_period: 0.002
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10
  joint_names:
    - nj_joint_1
    - nj_joint_2
    - nj_joint_3
    - nj_joint_4
    - nj_joint_5
    - nj_joint_6
  base_link: world
  tool_link: nj_flange
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.002

  initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
