kuka_level0_hw:
  type           : cnr/control/FakeRobotHW
  appenders      : [file, screen]
  levels         : [debug, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : kuka_level0_hw
  sampling_period: 0.002
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10
  joint_names:
    - structure_joint_1
    - kr_joint1
    - kr_joint2
    - kr_joint3
    - kr_joint4
    - kr_joint5
    - kr_joint6
  base_link: world
  tool_link: kr_flange
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.002

  initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
