kuka_level0_hw:
  type           : "cnr/control/TopicsRobotHW"
  appenders      : [file, screen]
  levels         : [trace, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : "kuka_level0_hw"
  sampling_period: 0.002
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10
  base_link: world
  tool_link: kuka_flange
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.002

  resources: [ joint_resource, wrench_resource ]  # this TopicsRobotHW manages topic of type: joint
  joint_resource:  # joint handles managed by planner_hw
    joint_names:  # name of the joint handles
    - kuka_joint1
    - kuka_joint2
    - kuka_joint3
    - kuka_joint4
    - kuka_joint5
    - kuka_joint6
    subscribed_topics:  # name of topics sensor_msgs/JointState which contains the state of the joint handle
    - /kuka/joint_states
    - /kuka/joint_states
    - /kuka/joint_states
    - /kuka/joint_states
    - /kuka/joint_states
    - /kuka/joint_states
    published_topics: # name of the topic (type sensor_msgs/JointState) that planner_hw will publish (it has to be only one)
    - /kuka/joint_target

  wrench_resource:
    sensor_name: kuka_wrench
    frame_id: kuka_gripper_base_link
    subscribed_topics:
    - /kuka/kuka_sensor_to_gripper_flange/wrench
