controller_list:
  - name: fake_kuka_controller
    type: $(arg fake_execution_type)
    joints:
      - kuka_joint1
      - kuka_joint2
      - kuka_joint3
      - kuka_joint4
      - kuka_joint5
      - kuka_joint6
initial:  # Define initial robot poses per group
#  - group: kuka
#    pose: home

  []