# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - kuka_jt_controller
    - comau_jt_controller

  kuka_jt_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - structure_joint_1
      - kuka_joint1
      - kuka_joint2
      - kuka_joint3
      - kuka_joint4
      - kuka_joint5
      - kuka_joint6
      
  comau_jt_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - comau_joint_1
      - comau_joint_2
      - comau_joint_3
      - comau_joint_4
      - comau_joint_5
      - comau_joint_6
