kuka:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kuka_joint1
    - kuka_joint2
    - kuka_joint3
    - kuka_joint4
    - kuka_joint5
    - kuka_joint6
  gains:
    kuka_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1