controller_list:
  - name: comau_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - nj_joint_1
      - nj_joint_2
      - nj_joint_3
      - nj_joint_4
      - nj_joint_5
      - nj_joint_6
  - name: kuka_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - structure_joint_1
      - kr_joint1
      - kr_joint2
      - kr_joint3
      - kr_joint4
      - kr_joint5
      - kr_joint6
