controller_list:
  - name: kuka
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - kuka_joint1
      - kuka_joint2
      - kuka_joint3
      - kuka_joint4
      - kuka_joint5
      - kuka_joint6