delta_utils:
  ros__parameters:
    control_word:
      controller_name: delta_controller
      command_interface: structure_joint_1/ctrl_word
    status_word:
      controller_name: delta_controller
      state_interface: structure_joint_1/status_word
    mode_of_operation:
      controller_name: delta_controller
      command_interface: structure_joint_1/moo
    mode_of_operation_display:
      controller_name: delta_controller
      state_interface: structure_joint_1/moo_display

    joint_trajectory_controller_name: kuka_scaled_fjt_controller #TODO: convert to list and add the controller for the COMAU robot

battery_cell_utils:
  ros__parameters:
    lubrication:
      command_controller_name: digital_io_controller
      command_interface: digital_outputs1/lubrication_command
      state_controller_name: digital_io_controller
      state_interface: digital_inputs/lubrication_state
    pneumatic_gripper:
      controller_name: digital_io_controller
      command_interface: digital_outputs1/pneumatic_gripper
      controlled_joint_name: pneumatic_gripper
    ati_sensor:
      controller_name: ft_ati_controller
      command_interface: analog_inputs/sensor_reset
      state_interfaces: # use the sequence of the sensor channels [force_x, force_y, force_z, torque_x, torque_y, torque_z]
      - analog_inputs/force_x
      - analog_inputs/force_y
      - analog_inputs/force_z
      - analog_inputs/torque_x 
      - analog_inputs/torque_y
      - analog_inputs/torque_z
      published_topic: /kuka_sensor/wrench
      publication_rate: 1000.0
      frame_id: kuka_gripper_base_link
    gpio: # THIS PARAMS SHOLD BE READ FROM FILE ROS2_CONTROLLER_CONFIG.YAML IN THIS NODE -> TO FIX!
      command_controller_name: digital_io_controller
      command_interfaces:
        - digital_outputs1/lubrication_command
        - digital_outputs1/d_output.1
        - digital_outputs1/pneumatic_gripper
        - digital_outputs1/d_output.3
        - digital_outputs1/d_output.4
        - digital_outputs1/d_output.5
        - digital_outputs1/d_output.6
        - digital_outputs1/d_output.7
        - digital_outputs2/d_output.0
        - digital_outputs2/d_output.1
        - digital_outputs2/d_output.2
        - digital_outputs2/d_output.3
        - digital_outputs2/d_output.4
        - digital_outputs2/screwdriver_hp # (screwdriver high pressure) [CABLE LABEL: AV ALTA]
        - digital_outputs2/d_output.6
        - digital_outputs2/screwdriver_lp # (screwdriver low pressure) [CABLE LABEL: AV BASSA] 
      state_controller_name: digital_io_controller
      state_interfaces:
        - digital_inputs/lubrication_state
        - digital_inputs/limit_switch_homing
        - digital_inputs/limit_switch_end
        - digital_inputs/d_input.3
        - digital_inputs/d_input.4
        - digital_inputs/d_input.5
        - digital_inputs/d_input.6
        - digital_inputs/d_input.7

