# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kuka_jt_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    comau_jt_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    delta_controller:
      type: ethercat_utils/GPIOController


    digital_io_controller:
      type: ethercat_utils/GPIOController


    ft_ati_controller:
      type: ethercat_utils/GPIOController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kuka_jt_controller:
  ros__parameters:
    joints:
      - structure_joint_1
      - kuka_joint1
      - kuka_joint2
      - kuka_joint3
      - kuka_joint4
      - kuka_joint5
      - kuka_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
comau_jt_controller:
  ros__parameters:
    joints:
      - comau_joint_1
      - comau_joint_2
      - comau_joint_3
      - comau_joint_4
      - comau_joint_5
      - comau_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
delta_controller:
  ros__parameters:
    joints:
      []
digital_io_controller:
  ros__parameters:
    joints:
      []
ft_ati_controller:
  ros__parameters:
    joints:
      []