<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="comau_setup"  params="prefix:='' use_fake_hardware='false'">
    <xacro:property name="nj_prefix" value="'comau_'" />
    <xacro:property name="basement_lenght_x" value="1.11" />
    <xacro:property name="basement_lenght_y" value="1.01" />
    <xacro:property name="basement_lenght_z" value="0.028" />

    <link name="${prefix}${nj_prefix}basement">
      <inertial>
        <origin xyz="0 0 00" rpy="0 0 0" />
        <mass value="10000" />
        <inertia
          ixx="0.1"
          ixy="0.0"
          ixz="0.0"
          iyy="0.1"
          iyz="0.0"
          izz="0.1" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 ${basement_lenght_z/2}"
          rpy="0 0 0" />
        <geometry>
          <box size="${basement_lenght_x} ${basement_lenght_y} ${basement_lenght_z}"/>
        </geometry>
        <material
          name="">
          <color
            rgba="0.1176 0.5059 0.6902 1" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="${basement_lenght_x/2} ${basement_lenght_y/2} ${basement_lenght_z/2}"
          rpy="0 0 0" />
        <geometry>
          <box size="${basement_lenght_x} ${basement_lenght_y} ${basement_lenght_z}"/>
        </geometry>
      </collision>
    </link>

    <xacro:include filename="$(find nj_220_2_7_description)/urdf/nj_220_2_7.xacro" />
    <xacro:nj_220_2_7 prefix="${prefix}${nj_prefix}"/>

    <joint name="${prefix}${nj_prefix}basement_to_robot" type="fixed">
      <origin
        xyz="0 0 ${basement_lenght_z}"
        rpy="0 0 0" />
      <parent link="${prefix}${nj_prefix}basement"/>
      <child link="${prefix}${nj_prefix}base_link"/>
    </joint>

  <!-- increased collisions -->
    <xacro:property name="fake_robot_lenght_x" value="4" />
    <xacro:property name="fake_robot_lenght_y" value="3" />
    <xacro:property name="fake_robot_lenght_z" value="3" />

    <joint name="${prefix}${nj_prefix}fake_robot" type="fixed">
      <origin
        xyz="-0.05 -0.05 0"
        rpy="0 0 0" />
      <parent link="${prefix}${nj_prefix}base_link"/>
      <child link="${prefix}${nj_prefix}fake_robot"/>
    </joint>
    <link name="${prefix}${nj_prefix}fake_robot">
      <inertial>
        <origin xyz="0 0 00" rpy="0 0 0" />
        <mass value="10000" />
        <inertia
          ixx="0.1"
          ixy="0.0"
          ixz="0.0"
          iyy="0.1"
          iyz="0.0"
          izz="0.1" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 ${fake_robot_lenght_z/2}"
          rpy="0 0 0" />
        <geometry>
          <box size="${fake_robot_lenght_x} ${fake_robot_lenght_y} ${fake_robot_lenght_z}"/>
        </geometry>
        <material
          name="">
          <color
            rgba="0.1176 0.5059 0.6902 0.5" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="0 0 ${fake_robot_lenght_z/2}"
          rpy="0 0 0" />
        <geometry>
          <box size="${fake_robot_lenght_x} ${fake_robot_lenght_y} ${fake_robot_lenght_z}"/>
        </geometry>
      </collision>
    </link>
  <!-- end increased collisions -->


  </xacro:macro>
</robot>