<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="kuka_setup"  params="prefix:='' robot_name:='kuka' use_fake_hardware='false' type:=rviz">

    <xacro:include filename="$(find kuka_structure_description)/urdf/kuka_structure.xacro" />
    <xacro:property name="kuka_structure_prefix" value="'structure_'" />
    <xacro:property name="kuka_structure_name" value="'kuka_structure'" />
    <xacro:kuka_structure prefix="${prefix}${kuka_structure_prefix}"
                          name="${prefix}${kuka_structure_name}"
                          use_fake_hardware="${use_fake_hardware}"/>

    <xacro:include filename="$(find kr_50_r2500_description)/urdf/kr_50_r2500.xacro" />
    <xacro:property name="kuka_prefix" value="'kuka_'" />
    <xacro:property name="kuka_name" value="'kuka'" />
    <xacro:kr_50_r2500 prefix="${prefix}${kuka_prefix}"
                       name="${prefix}${kuka_name}"
                       use_fake_hardware="${use_fake_hardware}" />

    <xacro:include filename="$(find schunk_gripper_jpg_p_160_description)/urdf/schunk_gripper_jpg_p_160.xacro" />
    <xacro:property name="gripper_prefix" value="'gripper_'" />
    <xacro:schunk_gripper_jpg_p_160 prefix="${prefix}${gripper_prefix}"  type="${type}"/>

    <joint name="kuka_structure_to_kr_50_r2500" type="fixed">
        <origin
          xyz="0.333 -0.035 0.325"
          rpy="0 ${pi/2} 0" />
        <parent link="${prefix}${kuka_structure_prefix}link_1"/>
        <child link="${prefix}${kuka_prefix}base_link"/>
    </joint>

    <joint name="${prefix}${kuka_prefix}robot_to_sensor_flange1" type="fixed">
        <origin
          xyz="0 0 0"
          rpy="0 0 1.5708" />
        <parent link="${prefix}${kuka_prefix}flange"/>
        <child link="${prefix}${kuka_prefix}sensor_flange1"/>
    </joint>
    <link name="${prefix}${kuka_prefix}sensor_flange1">
      <inertial>
        <origin xyz="-0 0 0.0094" rpy="0 0 0" />
        <mass value="0.365" />
        <inertia
          ixx="0.00052332"
          ixy="0.00000000"
          ixz="0.00000000"
          iyy="0.00052259"
          iyz="0.00000002"
          izz="0.00094820" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor_flange_robot_side.STL" />
        </geometry>
        <material
          name="">
          <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor_flange_robot_side.STL" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}${kuka_prefix}sensor_flange1_sensor_flange2" type="fixed">
        <origin
          xyz="0 0 0.02"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_prefix}sensor_flange1"/>
        <child link="${prefix}${kuka_prefix}sensor_flange2"/>
    </joint>
    <link name="${prefix}${kuka_prefix}sensor_flange2">
      <inertial>
        <origin xyz="0 -0.00000241 0.01069809" rpy="0 0 0" />
        <mass value="0.337" />
        <inertia
          ixx="0.00052069"
          ixy="0.00000000"
          ixz="0.00000000"
          iyy="0.00052072"
          iyz="0.00000005"
          izz="0.00094051" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor_flange_sensor_side.STL" />
        </geometry>
        <material
          name="">
          <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor_flange_sensor_side.STL" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}${kuka_prefix}sensor_flange2_to_sensor" type="fixed">
        <origin
          xyz="0 0 0.02"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_prefix}sensor_flange2"/>
        <child link="${prefix}${kuka_prefix}sensor"/>
    </joint>
    <link name="${prefix}${kuka_prefix}sensor">
      <inertial>
        <origin xyz="0 -0.00008976 0.01514808" rpy="0 0 0" />
        <mass value="0.169" />
        <inertia
          ixx="0.00014141"
          ixy="0.00000000"
          ixz="0.00000000"
          iyy="0.00014192"
          iyz="-0.00000021"
          izz="0.00018592" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor.STL" />
        </geometry>
        <material
          name="">
          <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://battery_cell_description/meshes/sensor.STL" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}${kuka_prefix}sensor_to_gripper_flange" type="fixed">
        <origin
          xyz="0 0 0.0286"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_prefix}sensor"/>
        <child link="${prefix}${kuka_prefix}gripper_flange"/>
    </joint>
    <link name="${prefix}${kuka_prefix}gripper_flange">
      <inertial>
        <origin xyz="0 0.00001675 0.00750175" rpy="0 0 0" />
        <mass value="0.12657298" />
        <inertia
          ixx="0.00006223"
          ixy="-0.00000035"
          ixz="0.00000000"
          iyy="0.00016947"
          iyz="-0.00000000"
          izz="0.00021258" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://schunk_gripper_jpg_p_160_description/meshes/sensor_to_gripper_flange.STL" />
        </geometry>
        <material
          name="">
          <color
            rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
        </material>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="package://schunk_gripper_jpg_p_160_description/meshes/sensor_to_gripper_flange.STL" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}gripper_joint" type="fixed">
      <origin xyz="0 0 0.015" rpy="0 0 0"/>
      <parent link="${prefix}${kuka_prefix}gripper_flange" />
      <child link="${prefix}${gripper_prefix}base" />
    </joint>

<!-- increased collisions -->
    <xacro:if value="${type == 'rviz'}">
      <xacro:property name="fake_foot_lenght_x" value="0.87" />
      <xacro:property name="fake_foot_lenght_y" value="1.5" />
      <xacro:property name="fake_foot_lenght_z" value="1.3" />

      <xacro:property name="fake_structure_lenght_x" value="4.3" />
      <xacro:property name="fake_structure_lenght_y" value="1.5" />
      <xacro:property name="fake_structure_lenght_z" value="4.0" />

      <joint name="${prefix}${kuka_prefix}fake_structure_right_foot" type="fixed">
        <origin
          xyz="-0.05 -0.05 0"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_structure_prefix}base_link"/>
        <child link="${prefix}${kuka_structure_prefix}fake_structure_right_foot"/>
      </joint>
      <link name="${prefix}${kuka_structure_prefix}fake_structure_right_foot">
        <inertial>
          <origin xyz="0 0 00" rpy="0 0 0" />
          <mass value="10000" />
          <inertia
            ixx="0.1"
            ixy="0.0"
            ixz="0.0"
            iyy="0.1"
            iyz="0.0"
            izz="0.1" />
        </inertial>
        <visual>
          <origin
            xyz="${fake_foot_lenght_x/2} ${fake_foot_lenght_y/2} ${fake_foot_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_foot_lenght_x} ${fake_foot_lenght_y} ${fake_foot_lenght_z}"/>
          </geometry>
          <material
            name="">
            <color
              rgba="0.1176 0.5059 0.6902 0.5" />
          </material>
        </visual>
        <collision>
          <origin
            xyz="${fake_foot_lenght_x/2} ${fake_foot_lenght_y/2} ${fake_foot_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_foot_lenght_x} ${fake_foot_lenght_y} ${fake_foot_lenght_z}"/>
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}${kuka_prefix}fake_structure_left_foot" type="fixed">
        <origin
          xyz="2.45 -0.05  0"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_structure_prefix}base_link"/>
        <child link="${prefix}${kuka_structure_prefix}fake_structure_left_foot"/>
      </joint>
      <link name="${prefix}${kuka_structure_prefix}fake_structure_left_foot">
        <inertial>
          <origin xyz="0 0 00" rpy="0 0 0" />
          <mass value="10000" />
          <inertia
            ixx="0.1"
            ixy="0.0"
            ixz="0.0"
            iyy="0.1"
            iyz="0.0"
            izz="0.1" />
        </inertial>
        <visual>
          <origin
            xyz="${fake_foot_lenght_x/2} ${fake_foot_lenght_y/2} ${fake_foot_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_foot_lenght_x} ${fake_foot_lenght_y} ${fake_foot_lenght_z}"/>
          </geometry>
          <material
            name="">
            <color
              rgba="0.1176 0.5059 0.6902 0.5" />
          </material>
        </visual>
        <collision>
          <origin
            xyz="${fake_foot_lenght_x/2} ${fake_foot_lenght_y/2} ${fake_foot_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_foot_lenght_x} ${fake_foot_lenght_y} ${fake_foot_lenght_z}"/>
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}${kuka_prefix}fake_structure" type="fixed">
        <origin
          xyz="-0.45 0.2  0"
          rpy="0 0 0" />
        <parent link="${prefix}${kuka_structure_prefix}base_link"/>
        <child link="${prefix}${kuka_structure_prefix}fake_structure"/>
      </joint>
      <link name="${prefix}${kuka_structure_prefix}fake_structure">
        <inertial>
          <origin xyz="0 0 00" rpy="0 0 0" />
          <mass value="10000" />
          <inertia
            ixx="0.1"
            ixy="0.0"
            ixz="0.0"
            iyy="0.1"
            iyz="0.0"
            izz="0.1" />
        </inertial>
        <visual>
          <origin
            xyz="${fake_structure_lenght_x/2} ${fake_structure_lenght_y/2} ${fake_structure_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_structure_lenght_x} ${fake_structure_lenght_y} ${fake_structure_lenght_z}"/>
          </geometry>
          <material
            name="">
            <color
              rgba="0.1176 0.5059 0.6902 0.5" />
          </material>
        </visual>
        <collision>
          <origin
            xyz="${fake_structure_lenght_x/2} ${fake_structure_lenght_y/2} ${fake_structure_lenght_z/2}"
            rpy="0 0 0" />
          <geometry>
            <box size="${fake_structure_lenght_x} ${fake_structure_lenght_y} ${fake_structure_lenght_z}"/>
            </geometry>
        </collision>
      </link>
    </xacro:if>
<!-- end increased collisions -->

  </xacro:macro>

</robot>