parallel_2f_gripper:
  sample_period: 1.0e-3

  # Publish all joint states -----------------------------------
  gripper_controller:
    type: robot_control/MimicEffortController
    joint_names:
    - right_finger_joint
    - left_finger_joint

    leading_joint: "right_finger_joint"
    setpoint_topic_name: "/gripper/joint_target"
    multiplier: [1.0, 1.0]
    offset: [0.0, 0.0]
